[package]
name = "gamerunner"
version = "0.1.0"
authors = ["SleepingPills <tom.farnbauer@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
neutronium = { path = "../../lib/neutronium" }
byteorder = "*"
