[package]
name = "gamecore"
version = "0.1.0"
authors = ["SleepingPills <tom.farnbauer@gmail.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_derive = "*"
serdeconv = "*"
flux = { path = "../../lib/flux" }
neutronium = { path = "../../lib/neutronium" }