[globa]
log = "off"
limits = { forms = 32768 }

[development]
address = "localhost"
port = 8000
workers = 2

[staging]
address = "0.0.0.0"
port = 80
workers = 2

[production]
address = "0.0.0.0"
port = 80
workers = 4