[package]
name = "t51server"
version = "0.1.0"
authors = ["SleepingPills <tom.farnbauer@gmail.com>"]
edition = "2018"

[dependencies]
t51core = { path = "../t51core" }
t51core_proc = { path = "../t51core_proc" }
byteorder = "*"
