[package]
name = "util"
version = "0.1.0"
authors = ["SleepingPills <tom.farnbauer@gmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
rand = "*"
chrono = "*"
serde_json = "*"
authenticator = { path = "../lib/authenticator" }
